### ISSUE TITLE
Does this project have anything to do with artificial neural networks?

### ISSUE THREAD

**Issue by cuong369** [budhiahimanshu96/Text-Semantic-Similarity-MachineLearning#1]
sorry. I want to ask a question. Hope you guys answer.
Does this project have anything to do with artificial neural networks?
Which neural network is used in the project?
What algorithm does the project use?
thank you so much. i love india

**Comment by budhiahimanshu96** [comment]
So, we have not used any Neural Network and also the algorithm we use is not based on Machine Learning. It basically uses the built-in machine learning library for NLP to find similarity between words in two different texts, then we assign weights to similarity indexes and use it as a measure to classify the texts. It is flawed on some levels as you may read in the README file.
