### ISSUE TITLE
This project is completely useless!

### ISSUE THREAD

**Issue by chinmay1d** [budhiahimanshu96/Text-Semantic-Similarity-MachineLearning#2]
I checked it with two completely different sentences having completely different meaning, and yet it said "some what similar"

**Comment by budhiahimanshu96** [comment]
So, yes this is not a perfect thing. This is a drawback of our libraries as it compares just works and similarity is just given between words. Also, the algorithm we deploy is just word by word similarity. So, it gives false positives.
